"""initial schema

Revision ID: 172828cda95b
Revises: 
Create Date: 2026-07-28 23:05:38.506204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172828cda95b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('match_kind', sa.String(length=16), nullable=False),
    sa.Column('perenual_id', sa.Integer(), nullable=True),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('watering', sa.String(length=64), nullable=True),
    sa.Column('sunlight', sa.JSON(), nullable=True),
    sa.Column('cycle', sa.String(length=64), nullable=True),
    sa.Column('poisonous_to_pets', sa.Boolean(), nullable=True),
    sa.Column('poisonous_to_humans', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_cache_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('species_cache_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['species_cache_id'], ['species_cache.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_species_cache_id'), ['species_cache_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_user_id'), ['user_id'], unique=False)

    op.create_table('watering_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('watered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watering_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watering_events_plant_id'), ['plant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watering_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watering_events_plant_id'))

    op.drop_table('watering_events')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_user_id'))
        batch_op.drop_index(batch_op.f('ix_plants_species_cache_id'))

    op.drop_table('plants')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('species_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_cache_normalized_name'))

    op.drop_table('species_cache')
    # ### end Alembic commands ###
