"""add matched_name to species cache

Revision ID: 5cb4d83162de
Revises: e1154da1bb05
Create Date: 2026-07-29 13:10:11.127668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb4d83162de'
down_revision: Union[str, Sequence[str], None] = 'e1154da1bb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_cache', schema=None) as batch_op:
        batch_op.drop_column('matched_name')

    # ### end Alembic commands ###
